

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Hub : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Hub entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Hub()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Hub(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Hub> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Hub.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hub_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hub_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ClientId
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.ClientId);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.ClientId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long Lat
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Lat);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Lat, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lat_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lat_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lat_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long Lon
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Lon);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Lon, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lon_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lon_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lon_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MapX
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.MapX);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.MapX, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MapX_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MapX_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MapX_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MapY
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.MapY);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.MapY, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MapY_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MapY_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MapY_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Descriptions
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Descriptions);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Descriptions, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descriptions_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descriptions_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descriptions_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Detail
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Detail);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Detail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ParentHubId
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.ParentHubId);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.ParentHubId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ParentHubId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ParentHubId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ParentHubId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Client Client
        {
            get
            {
                return global::LightSwitchApplication.Hub.DetailsClass.GetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Client);
            }
            set
            {
                global::LightSwitchApplication.Hub.DetailsClass.SetValue(this, global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Client, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Hub,
                global::LightSwitchApplication.Hub.DetailsClass,
                global::LightSwitchApplication.Hub.DetailsClass.IImplementation,
                global::LightSwitchApplication.Hub.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass>.Entry
                __HubEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass>.Entry(
                    global::LightSwitchApplication.Hub.DetailsClass.__Hub_CreateNew,
                    global::LightSwitchApplication.Hub.DetailsClass.__Hub_Created,
                    global::LightSwitchApplication.Hub.DetailsClass.__Hub_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Hub __Hub_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Hub> es)
            {
                return new global::LightSwitchApplication.Hub(es);
            }
            private static void __Hub_Created(global::LightSwitchApplication.Hub e)
            {
                e.Hub_Created();
            }
            private static bool __Hub_AllowSaveWithErrors(global::LightSwitchApplication.Hub e)
            {
                bool result = false;
                e.Hub_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Hub.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string> ClientId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.ClientId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long> Lat
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Lat) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long> Lon
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Lon) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int> MapX
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.MapX) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int> MapY
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.MapY) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string> Descriptions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Descriptions) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string> Detail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Detail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string> ParentHubId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.ParentHubId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, global::LightSwitchApplication.Client> Client
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Client) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Name { get; set; }
                new string Description { get; set; }
                new string ClientId { get; set; }
                new long Lat { get; set; }
                new long Lon { get; set; }
                new int MapX { get; set; }
                new int MapY { get; set; }
                new string Descriptions { get; set; }
                new string Detail { get; set; }
                new string ParentHubId { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Client { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry
                    ClientId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry(
                        "ClientId",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ClientId_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ClientId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ClientId_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ClientId_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ClientId_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ClientId_OnValueChanged);
                private static void _ClientId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._ClientId, sf);
                }
                private static bool _ClientId_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.ClientId_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClientId_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClientId_Validate(r);
                }
                private static string _ClientId_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.ClientId;
                }
                private static void _ClientId_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ClientId = v;
                }
                private static void _ClientId_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.ClientId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Entry
                    Lat = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Entry(
                        "Lat",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lat_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lat_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lat_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lat_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lat_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lat_OnValueChanged);
                private static void _Lat_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Lat, sf);
                }
                private static bool _Lat_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Lat_IsReadOnly(ref result);
                    return result;
                }
                private static void _Lat_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Lat_Validate(r);
                }
                private static long _Lat_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Lat;
                }
                private static void _Lat_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, long v)
                {
                    d.ImplementationEntity.Lat = v;
                }
                private static void _Lat_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Lat_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Entry
                    Lon = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Entry(
                        "Lon",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lon_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lon_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lon_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lon_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lon_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Lon_OnValueChanged);
                private static void _Lon_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Lon, sf);
                }
                private static bool _Lon_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Lon_IsReadOnly(ref result);
                    return result;
                }
                private static void _Lon_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Lon_Validate(r);
                }
                private static long _Lon_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Lon;
                }
                private static void _Lon_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, long v)
                {
                    d.ImplementationEntity.Lon = v;
                }
                private static void _Lon_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Lon_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Entry
                    MapX = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Entry(
                        "MapX",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapX_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapX_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapX_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapX_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapX_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapX_OnValueChanged);
                private static void _MapX_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._MapX, sf);
                }
                private static bool _MapX_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.MapX_IsReadOnly(ref result);
                    return result;
                }
                private static void _MapX_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MapX_Validate(r);
                }
                private static int _MapX_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.MapX;
                }
                private static void _MapX_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, int v)
                {
                    d.ImplementationEntity.MapX = v;
                }
                private static void _MapX_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.MapX_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Entry
                    MapY = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Entry(
                        "MapY",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapY_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapY_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapY_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapY_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapY_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._MapY_OnValueChanged);
                private static void _MapY_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._MapY, sf);
                }
                private static bool _MapY_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.MapY_IsReadOnly(ref result);
                    return result;
                }
                private static void _MapY_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MapY_Validate(r);
                }
                private static int _MapY_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.MapY;
                }
                private static void _MapY_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, int v)
                {
                    d.ImplementationEntity.MapY = v;
                }
                private static void _MapY_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.MapY_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry
                    Descriptions = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry(
                        "Descriptions",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Descriptions_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Descriptions_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Descriptions_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Descriptions_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Descriptions_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Descriptions_OnValueChanged);
                private static void _Descriptions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Descriptions, sf);
                }
                private static bool _Descriptions_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Descriptions_IsReadOnly(ref result);
                    return result;
                }
                private static void _Descriptions_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Descriptions_Validate(r);
                }
                private static string _Descriptions_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Descriptions;
                }
                private static void _Descriptions_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Descriptions = v;
                }
                private static void _Descriptions_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Descriptions_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry
                    Detail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry(
                        "Detail",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Detail_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Detail_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Detail_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Detail_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Detail_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Detail_OnValueChanged);
                private static void _Detail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Detail, sf);
                }
                private static bool _Detail_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Detail_IsReadOnly(ref result);
                    return result;
                }
                private static void _Detail_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Detail_Validate(r);
                }
                private static string _Detail_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Detail;
                }
                private static void _Detail_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Detail = v;
                }
                private static void _Detail_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Detail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry
                    ParentHubId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Entry(
                        "ParentHubId",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ParentHubId_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ParentHubId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ParentHubId_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ParentHubId_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ParentHubId_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._ParentHubId_OnValueChanged);
                private static void _ParentHubId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._ParentHubId, sf);
                }
                private static bool _ParentHubId_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.ParentHubId_IsReadOnly(ref result);
                    return result;
                }
                private static void _ParentHubId_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ParentHubId_Validate(r);
                }
                private static string _ParentHubId_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.ParentHubId;
                }
                private static void _ParentHubId_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ParentHubId = v;
                }
                private static void _ParentHubId_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.ParentHubId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Client = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Client",
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_Stub,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_ComputeIsReadOnly,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_Validate,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_GetCoreImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_GetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_SetImplementationValue,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_Refresh,
                        global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties._Client_OnValueChanged);
                private static void _Client_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Hub.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.Hub.DetailsClass d, object sf)
                {
                    c(d, ref d._Client, sf);
                }
                private static bool _Client_ComputeIsReadOnly(global::LightSwitchApplication.Hub e)
                {
                    bool result = false;
                    e.Client_IsReadOnly(ref result);
                    return result;
                }
                private static void _Client_Validate(global::LightSwitchApplication.Hub e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Client_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Client_GetCoreImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.ImplementationEntity.Client;
                }
                private static global::LightSwitchApplication.Client _Client_GetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass d, global::LightSwitchApplication.Client v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Client, ref d._Client, (i, ev) => i.Client = ev, v);
                }
                private static void _Client_Refresh(global::LightSwitchApplication.Hub.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Hub.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_OnValueChanged(global::LightSwitchApplication.Hub e)
                {
                    e.Client_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data _ClientId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Data _Lat;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, long>.Data _Lon;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Data _MapX;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, int>.Data _MapY;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data _Descriptions;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data _Detail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, string>.Data _ParentHubId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Hub, global::LightSwitchApplication.Hub.DetailsClass, global::LightSwitchApplication.Client>.Data _Client;
            
        }
    
        #endregion
    }
    
    #endregion
}
