

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Card : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Card entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Card()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Card(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Card> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Card.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Card_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Card_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ClientId
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.ClientId);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.ClientId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ImageURL
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.ImageURL);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.ImageURL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ImageURL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ImageURL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ImageURL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string VideoURL
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.VideoURL);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.VideoURL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VideoURL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VideoURL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VideoURL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Client Client
        {
            get
            {
                return global::LightSwitchApplication.Card.DetailsClass.GetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Client);
            }
            set
            {
                global::LightSwitchApplication.Card.DetailsClass.SetValue(this, global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Client, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Card,
                global::LightSwitchApplication.Card.DetailsClass,
                global::LightSwitchApplication.Card.DetailsClass.IImplementation,
                global::LightSwitchApplication.Card.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass>.Entry
                __CardEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass>.Entry(
                    global::LightSwitchApplication.Card.DetailsClass.__Card_CreateNew,
                    global::LightSwitchApplication.Card.DetailsClass.__Card_Created,
                    global::LightSwitchApplication.Card.DetailsClass.__Card_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Card __Card_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Card> es)
            {
                return new global::LightSwitchApplication.Card(es);
            }
            private static void __Card_Created(global::LightSwitchApplication.Card e)
            {
                e.Card_Created();
            }
            private static bool __Card_AllowSaveWithErrors(global::LightSwitchApplication.Card e)
            {
                bool result = false;
                e.Card_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Card.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string> ClientId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.ClientId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string> ImageURL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.ImageURL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string> VideoURL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.VideoURL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, global::LightSwitchApplication.Client> Client
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Client) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string ClientId { get; set; }
                new string Title { get; set; }
                new string Description { get; set; }
                new string ImageURL { get; set; }
                new string VideoURL { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Client { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, int>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry
                    ClientId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry(
                        "ClientId",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ClientId_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ClientId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ClientId_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ClientId_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ClientId_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ClientId_OnValueChanged);
                private static void _ClientId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._ClientId, sf);
                }
                private static bool _ClientId_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.ClientId_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClientId_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClientId_Validate(r);
                }
                private static string _ClientId_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.ClientId;
                }
                private static void _ClientId_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ClientId = v;
                }
                private static void _ClientId_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.ClientId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry
                    ImageURL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry(
                        "ImageURL",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ImageURL_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ImageURL_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ImageURL_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ImageURL_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ImageURL_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._ImageURL_OnValueChanged);
                private static void _ImageURL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._ImageURL, sf);
                }
                private static bool _ImageURL_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.ImageURL_IsReadOnly(ref result);
                    return result;
                }
                private static void _ImageURL_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ImageURL_Validate(r);
                }
                private static string _ImageURL_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.ImageURL;
                }
                private static void _ImageURL_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ImageURL = v;
                }
                private static void _ImageURL_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.ImageURL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry
                    VideoURL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Entry(
                        "VideoURL",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._VideoURL_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._VideoURL_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._VideoURL_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._VideoURL_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._VideoURL_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._VideoURL_OnValueChanged);
                private static void _VideoURL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._VideoURL, sf);
                }
                private static bool _VideoURL_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.VideoURL_IsReadOnly(ref result);
                    return result;
                }
                private static void _VideoURL_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VideoURL_Validate(r);
                }
                private static string _VideoURL_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.VideoURL;
                }
                private static void _VideoURL_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, string v)
                {
                    d.ImplementationEntity.VideoURL = v;
                }
                private static void _VideoURL_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.VideoURL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Client = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Client",
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_Stub,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_ComputeIsReadOnly,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_Validate,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_GetCoreImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_GetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_SetImplementationValue,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_Refresh,
                        global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties._Client_OnValueChanged);
                private static void _Client_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Card.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.Card.DetailsClass d, object sf)
                {
                    c(d, ref d._Client, sf);
                }
                private static bool _Client_ComputeIsReadOnly(global::LightSwitchApplication.Card e)
                {
                    bool result = false;
                    e.Client_IsReadOnly(ref result);
                    return result;
                }
                private static void _Client_Validate(global::LightSwitchApplication.Card e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Client_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Client_GetCoreImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.ImplementationEntity.Client;
                }
                private static global::LightSwitchApplication.Client _Client_GetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass d, global::LightSwitchApplication.Client v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Client, ref d._Client, (i, ev) => i.Client = ev, v);
                }
                private static void _Client_Refresh(global::LightSwitchApplication.Card.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Card.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_OnValueChanged(global::LightSwitchApplication.Card e)
                {
                    e.Client_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data _ClientId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data _ImageURL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, string>.Data _VideoURL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Card, global::LightSwitchApplication.Card.DetailsClass, global::LightSwitchApplication.Client>.Data _Client;
            
        }
    
        #endregion
    }
    
    #endregion
}
